name: skeleton_project_simple
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # state management
  get: ^4.6.5

  # http client and Firebase
  http: ^1.1.0
  dio: ^5.4.1
  alice: ^0.4.1

  # Firebase & Notification
  firebase_auth: ^4.16.0 
  firebase_storage: ^11.6.0
  firebase_app_check: ^0.2.1+8
  firebase_core: ^2.24.2

  #design
  delayed_display: ^2.0.0
  
  line_awesome_flutter: ^2.0.0
  keyboard_dismisser: ^3.0.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  # awesome_snackbar_content: ^0.1.3
  loading_animation_widget: ^1.2.0+4
  avatar_glow: ^3.0.1
  #intl_phone_number_input: ^0.7.3+1
  font_awesome_flutter: ^10.7.0
  icons_plus: ^5.0.0
  adaptive_dialog: ^1.10.1
  image_picker: ^1.0.7
  
  path: ^1.8.3
  r_nav_n_sheet: ^1.0.2
  remixicon: ^1.1.1
  custom_refresh_indicator: ^3.0.0
  sliver_app_bar_builder: ^1.1.0
  google_fonts: 6.1.0
  readmore: ^2.2.0
  typewritertext: ^3.0.2
  animated_text_kit: ^4.2.2
  file_picker: ^8.0.2
  flutter_staggered_grid_view: ^0.7.0
  table_calendar: ^3.0.9
  flutter_slidable: ^3.0.1
  shimmer: ^3.0.0
  animations: ^2.0.8
  timeago: ^3.6.1
  auto_animated: ^3.2.0
  flutter_staggered_animations: ^1.1.1
  searchable_listview: ^2.11.0
  syncfusion_flutter_pdfviewer: ^24.1.45
  flutter_rating_bar: ^4.0.1
  modular_ui: ^0.0.5
  percent_indicator: ^4.2.3
  fl_chart: ^0.67.0
  intl: ^0.19.0
  http_parser: ^4.0.2
  zoom_widget: ^2.0.1
  syncfusion_flutter_sliders: ^24.2.9
  lottie: ^3.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
